### ISSUE TITLE
Return Type Enum

### ISSUE THREAD

**Issue by nicolai0** [andogq/qubit#20]
I would like to be able to return an `enum` from a handler. Currently, it complains that the proc-macro derive panicked when deriving `ExportType`. This is especially important for error handling as I want to return a `Result<..., MyError>` type.

PS: Thanks for building this, it's exactly what I've been looking for!

**Comment by andogq** [comment]
Thanks for the report!

I've just pushed a fix, if you bump `qubit` to `0.2.1` hopefully your problem will be solved. Feel free to re-open if that doesn't do the trick.
