### ISSUE TITLE
Provide impl's for other crates

### ISSUE THREAD

**Issue by nicolai0** [andogq/qubit#26]
If you look at ts-rs it supports features that provide impl's for lots of external crates, like chrono and uuid (being the most important for me at least). Having something similar for this crate would be great.

PS: Would it be at all possible to support using types that only implement ts_rs::TS and not ExportType? If it is then I assume support like this feature request would come "for free". Just a thought, I have no idea about the feasability.

**Comment by andogq** [comment]
This should now be addressed if you bump `qubit` to `0.5.0`!

I've completely removed `ExportType` so you only need `ts_rs::TS`, and you should be free to use any combination of features and macro attributes that `ts-rs` offers, including features for other creates.

**Comment by nicolai0** [comment]
> I've completely removed ExportType

Awesome, nice work, and thanks!
