### ISSUE TITLE
Duplicate identifier 'Server' in generated bindings

### ISSUE THREAD

**Issue by nicolai0** [andogq/qubit#28]
If I declare a type called `Server` that impls `ExportType` then the resulting `bindings.ts` will have an error because there is always an exported type called `Server` that represents the qubit handlers.

Renaming it to something less generic would fix it for most cases.

**Comment by andogq** [comment]
As a temporary work around, I've changed this to export the server type as `QubitServer`. Down the road, I'll make it possible to provide an optional alternative name to export the type under when the bindings are generated.
