### ISSUE TITLE
@qubit/client is empty

### ISSUE THREAD

**Issue by nicolai0** [andogq/qubit#29]
I included it in my project, but checking the folder inside node_modules it's entirely empty besides package.json and CHANGELOG.md. It's clearly expecting a `dist` folder there, but it's not there.

<img width="245" alt="image" src="https://github.com/andogq/qubit/assets/5960736/ece884b3-fa87-411f-9190-650a77020602">

**Comment by andogq** [comment]
This should be fixed with `@qubit-rs/client@0.2.0`!
