### ISSUE TITLE
Types in tuples are not getting exported

### ISSUE THREAD

**Issue by nicolai0** [andogq/qubit#41]
If I have a handler like so:
```rust
#[handler]
pub async fn foo(context: Context) -> MyType {
  todo!()
}
```

then `MyType` correctly appears in the bindings folder. If I do this:
```rust
#[handler]
pub async fn foo(context: Context) -> (MyType, MyType) {
  todo!()
}
```

then `MyType` is not added to the bindings.

**Comment by andogq** [comment]
That should be addressed with qubit `0.5.2`!
