### ISSUE TITLE
Question: Can the generated index.ts export the other types?

### ISSUE THREAD

**Issue by gluax** [andogq/qubit#81]
Is there a way to have our custom types exported from the `index.ts` file somehow?
Just a QoL question I'm wondering if I can minimize imports like `import type { RpcError } from "./bindings/RpcError.ts";

![image](https://github.com/user-attachments/assets/03f1631a-0987-40af-a855-a27d5084e396)

For instance, if I wanted that `RpcError` exported from that index file for whatever reason.

I tried:
![image](https://github.com/user-attachments/assets/cefc7926-c1da-48f5-976a-c98dde004893)

Curious if this is possible!

**Comment by epatters** [comment]
I agree that this would be useful to have built in. As a workaround, I created a top-level `index.ts` that re-exports `QubitServer` plus other things I want, like this:

```typescript
export * from "./src";

export type { JsonValue } from "./src/serde_json/JsonValue";
export type { RpcResult } from "./src/RpcResult";
```

**Comment by andogq** [comment]
I've had a bit of a play around with this, and managed to get something simple enough working.

I'm foreseeing the a potential issue if the same type name is used in multiple places, as the current type exporting setup looses the 'namespaced' nature of Rust modules. For example, `src/file_a.rs` could export `MyStruct`, available at `crate::file_a::MyStruct`, whilst `src/file_b.rs` could export a different `MyString`, available at `crate::file_b::MyStruct`. This setup would cause a conflict with them both being imported and exported from the TS file as `type MyStruct`.

This can be solved with the [`#[ts(rename = "..")]`](https://docs.rs/ts-rs/latest/ts_rs/trait.TS.html) option however, but it's something worth being aware of.

**Comment by andogq** [comment]
Give `qubit@0.10.2` a try, this should be solved in there.

**Comment by gluax** [comment]
This worked thanks so much!

**Comment by epatters** [comment]
Works for me too. Thank you!
