### ISSUE TITLE
Is it possible to disable default features for TS-RS?

### ISSUE THREAD

**Issue by gluax** [andogq/qubit#91]
Hey!

I don't know if this would break anything for `qubit` but I ask because I have the following use case:

I'm fetching data from a request on the `rust` side which expects the JSON to be in `snake_case`.
But on the TS my linter yells at me for not using `camelCase`.

So I did the following:
```rust
#[derive(Debug, Serialize, Deserialize, Clone, TS)]
#[serde(rename_all = "snake_case")]
#[ts(rename_all = "camelCase")]
pub struct PubkeyParams {
    pub activation_delay:       String,
    pub activation_threshold_percent: u8,
}
```

however, it seems the `serde-compat` feature, enabled by default` overrides the ts-rs directive.
We can always enable this feature ourselves from where we import it if we want it.

Or maybe this is a issue I should put on `ts-rs`, that `ts` directives should override the `serde` directive if it exists.

EDIT:

I did wind up making an issue over on ts-rs as well: https://github.com/Aleph-Alpha/ts-rs/issues/375

**Comment by andogq** [comment]
https://serde.rs/container-attrs.html#rename_all

I'm not 100% sure it would work, but you could try this form of serde rename

```
#[serde(rename_all(serialize = "camelCase", deserialize = "snake_case"))]
```

That should give you the functionality you're looking for, as ts-rs is only used for generating the types, the serialisation is still handled by serde.

**Comment by andogq** [comment]
I'm going to close this for now, as there doesn't seem to be much that can be done within Qubit for this!
